/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlttgs;

import dao.frmCTMonHocDAO;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pojo.pCTMonHoc;

/**
 *
 * @author Admin
 */
public class frmCTMonHoc extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmCTMonHoc
     */
    public frmCTMonHoc() {
        initComponents();
        this.setSize(755, 539);
        this.setLocation(15,0);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        showds();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbThongTinLopHoc = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtCa = new javax.swing.JTextField();
        txtTenMH = new javax.swing.JTextField();
        txtMaMH = new javax.swing.JTextField();
        txtMaLop = new javax.swing.JTextField();
        txtMaGV = new javax.swing.JTextField();
        txtSoBuoi = new javax.swing.JTextField();
        lbDiaChi = new javax.swing.JLabel();
        lbNgaySinh = new javax.swing.JLabel();
        lbGioiTinh = new javax.swing.JLabel();
        lbMaHV = new javax.swing.JLabel();
        lbTenHV = new javax.swing.JLabel();
        lbSDT = new javax.swing.JLabel();
        lbTrangThai = new javax.swing.JLabel();
        cbxTrangThai = new javax.swing.JComboBox<>();
        txtTongBuoi = new javax.swing.JTextField();
        lbDiaChi1 = new javax.swing.JLabel();
        txtNgayBD = new javax.swing.JTextField();
        lbDiaChi2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnDong = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDSMH = new javax.swing.JTable();

        getContentPane().setLayout(null);

        lbThongTinLopHoc.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbThongTinLopHoc.setText("THÔNG TIN MÔN HỌC");
        getContentPane().add(lbThongTinLopHoc);
        lbThongTinLopHoc.setBounds(240, 10, 300, 29);

        jPanel2.setLayout(null);
        jPanel2.add(txtCa);
        txtCa.setBounds(70, 90, 120, 30);
        jPanel2.add(txtTenMH);
        txtTenMH.setBounds(70, 50, 120, 30);

        txtMaMH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaMHActionPerformed(evt);
            }
        });
        jPanel2.add(txtMaMH);
        txtMaMH.setBounds(70, 10, 120, 30);
        jPanel2.add(txtMaLop);
        txtMaLop.setBounds(270, 10, 120, 30);
        jPanel2.add(txtMaGV);
        txtMaGV.setBounds(270, 50, 120, 30);
        jPanel2.add(txtSoBuoi);
        txtSoBuoi.setBounds(270, 90, 120, 30);

        lbDiaChi.setText("Đã Học:");
        jPanel2.add(lbDiaChi);
        lbDiaChi.setBounds(200, 90, 70, 30);

        lbNgaySinh.setText("Mã GV:");
        jPanel2.add(lbNgaySinh);
        lbNgaySinh.setBounds(200, 50, 70, 30);

        lbGioiTinh.setText("Mã Lớp:");
        jPanel2.add(lbGioiTinh);
        lbGioiTinh.setBounds(200, 10, 70, 30);

        lbMaHV.setText("Mã MH:");
        jPanel2.add(lbMaHV);
        lbMaHV.setBounds(10, 10, 60, 30);

        lbTenHV.setText("Tên MH:");
        jPanel2.add(lbTenHV);
        lbTenHV.setBounds(10, 50, 60, 30);

        lbSDT.setText("Ca Học:");
        jPanel2.add(lbSDT);
        lbSDT.setBounds(10, 90, 60, 30);

        lbTrangThai.setText("Trạng thái:");
        jPanel2.add(lbTrangThai);
        lbTrangThai.setBounds(410, 10, 80, 30);

        cbxTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đang dạy", "Chưa Mở Lớp", "Hoàn Thành" }));
        cbxTrangThai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTrangThaiActionPerformed(evt);
            }
        });
        jPanel2.add(cbxTrangThai);
        cbxTrangThai.setBounds(480, 10, 120, 30);
        jPanel2.add(txtTongBuoi);
        txtTongBuoi.setBounds(480, 90, 120, 30);

        lbDiaChi1.setText("Tổng Buổi:");
        jPanel2.add(lbDiaChi1);
        lbDiaChi1.setBounds(410, 90, 70, 30);
        jPanel2.add(txtNgayBD);
        txtNgayBD.setBounds(480, 50, 120, 30);

        lbDiaChi2.setText("Ngày BD:");
        jPanel2.add(lbDiaChi2);
        lbDiaChi2.setBounds(410, 50, 70, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(70, 50, 620, 160);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        btnDong.setText("Đóng");
        btnDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDongActionPerformed(evt);
            }
        });
        jPanel1.add(btnDong);
        btnDong.setBounds(380, 10, 100, 30);

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        jPanel1.add(btnThem);
        btnThem.setBounds(20, 10, 100, 30);

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        jPanel1.add(btnSua);
        btnSua.setBounds(140, 10, 100, 30);

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        jPanel1.add(btnXoa);
        btnXoa.setBounds(260, 10, 100, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(120, 430, 500, 50);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tblDSMH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã môn", "Tên Môn học", "Mã Lớp", "Mã GV", "Ca", "Ngày bắt đầu", "Số buổi đã học", "Tổng buổi", "Trạng thái"
            }
        ));
        tblDSMH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDSMHMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDSMH);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 220, 660, 190);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaMHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaMHActionPerformed

    private void cbxTrangThatxtMaMHPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTrangThaiActionPerformed

    }//GEN-LAST:event_cbxTrangThaiActionPerformed

    private void cbxTrangThaiActionPerformed(java.awt.event.ActionEvent evt) {                                             
        
    }   
    private void btnDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDongActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnDongActionPerformed

    private void tblDSMHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDSMHMouseClicked
                // TODO add your handling code here:
                int row = tblDSMH.getSelectedRow();
                txtMaMH.setText((String)tblDSMH.getValueAt(row, 0));
                txtTenMH.setText((String)tblDSMH.getValueAt(row, 1));
                txtMaLop.setText((String)tblDSMH.getValueAt(row, 2));
                txtMaGV.setText((String)tblDSMH.getValueAt(row, 3));
                txtCa.setText((String)tblDSMH.getValueAt(row, 4));
                txtNgayBD.setText((String)tblDSMH.getValueAt(row, 5));
                txtSoBuoi.setText((String)tblDSMH.getValueAt(row, 6).toString());
                txtTongBuoi.setText((String)tblDSMH.getValueAt(row, 7).toString());
                cbxTrangThai.getModel().setSelectedItem(tblDSMH.getValueAt(row, 8).toString());
    }//GEN-LAST:event_tblDSMHMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        if (frmCTMonHocDAO.KTTT(txtMaMH.getText()) == true) {
            JOptionPane.showConfirmDialog(null, "Mã đã tồn tại! Xin vui lòng kiểm tra lại!","Thông báo!",JOptionPane.OK_OPTION);
            return;
        }
        else{
            String maMH = txtMaMH.getText();
            String tenMH = txtTenMH.getText();
            String maLop = txtMaLop.getText();
            String maGV = txtMaGV.getText();
            String Ca = txtCa.getText();
            String ngayBD = txtNgayBD.getText();
            String tongBuoi = txtTongBuoi.getText();
            String soBuoi = txtSoBuoi.getText();
            String trangThai = cbxTrangThai.getSelectedItem().toString();
            pCTMonHoc mh = new pCTMonHoc();
            mh.setMaMH(maMH);
            mh.setTenMH(tenMH);
            mh.setMaLop(maLop);
            mh.setMaGV(maGV);
            mh.setCa(Ca);
            mh.setNgayBD(ngayBD);
            mh.setTongBuoi(Integer.parseInt(tongBuoi));
            mh.setSoBuoi(Integer.parseInt(soBuoi));
            mh.setTrangThai(trangThai);
            boolean kq = frmCTMonHocDAO.Add(mh);
            if ( kq == true) {
                JOptionPane.showMessageDialog(null, "Thêm thành công!");
                showds();
            }
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        if (frmCTMonHocDAO.KTTT(txtMaMH.getText()) == false) {
            JOptionPane.showConfirmDialog(null, "Mã không tồn tại! Xin vui lòng kiểm tra lại!","Thông báo!",JOptionPane.OK_OPTION);
            return;
        }
        else
        {
            String maMH = txtMaMH.getText();
            
            boolean kq = frmCTMonHocDAO.Delete(maMH);
            if (kq == true) {
                JOptionPane.showMessageDialog(null, "Xóa thành công!");
                showds();
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        String maMH = txtMaMH.getText();
        String tenMH = txtTenMH.getText();
        String maLop = txtMaLop.getText();
        String maGV = txtMaGV.getText();
        String Ca = txtCa.getText();
        String ngayBD = txtNgayBD.getText();
        String tongBuoi = txtTongBuoi.getText();
        String soBuoi = txtSoBuoi.getText();
        String trangThai = cbxTrangThai.getSelectedItem().toString();
        pCTMonHoc mh = new pCTMonHoc();
        mh.setMaMH(maMH);
        mh.setTenMH(tenMH);
        mh.setMaLop(maLop);
        mh.setMaGV(maGV);
        mh.setCa(Ca);
        mh.setNgayBD(ngayBD);
        mh.setTongBuoi(Integer.parseInt(tongBuoi));
        mh.setSoBuoi(Integer.parseInt(soBuoi));
        mh.setTrangThai(trangThai);
        boolean kq = frmCTMonHocDAO.Update(maMH, mh);
        if (kq == true) {
            JOptionPane.showMessageDialog(null, "Sửa thành công!");
                showds();
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void showds(){
        DefaultTableModel dtm = (DefaultTableModel)tblDSMH.getModel();
        dtm.setRowCount(0);
        frmCTMonHocDAO.ShowData2(dtm);
        tblDSMH.setModel(dtm);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDong;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbxTrangThai;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbDiaChi;
    private javax.swing.JLabel lbDiaChi1;
    private javax.swing.JLabel lbDiaChi2;
    private javax.swing.JLabel lbGioiTinh;
    private javax.swing.JLabel lbMaHV;
    private javax.swing.JLabel lbNgaySinh;
    private javax.swing.JLabel lbSDT;
    private javax.swing.JLabel lbTenHV;
    private javax.swing.JLabel lbThongTinLopHoc;
    private javax.swing.JLabel lbTrangThai;
    private javax.swing.JTable tblDSMH;
    private javax.swing.JTextField txtCa;
    private javax.swing.JTextField txtMaGV;
    private javax.swing.JTextField txtMaLop;
    private javax.swing.JTextField txtMaMH;
    private javax.swing.JTextField txtNgayBD;
    private javax.swing.JTextField txtSoBuoi;
    private javax.swing.JTextField txtTenMH;
    private javax.swing.JTextField txtTongBuoi;
    // End of variables declaration//GEN-END:variables
}
