/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlttgs;

import dao.frmCTLopDAO;
import java.awt.List;
import java.sql.PreparedStatement;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.DefaultCellEditor;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pojo.pCTLop;

/**
 *
 * @author Admin
 */
public class frmCTLopHoc extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmCTLopHoc
     */
    public frmCTLopHoc() {
        initComponents();
        this.setLocation(60,60);
        this.setSize(655, 430);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        ShowData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCTLop = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnDong = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        lbNgayBD1 = new javax.swing.JLabel();
        txtMaMH = new javax.swing.JTextField();
        txtMaGV = new javax.swing.JTextField();
        txtCaHoc = new javax.swing.JTextField();
        lbTrangThai = new javax.swing.JLabel();
        lbThongTinLopHoc = new javax.swing.JLabel();
        lbNgayBD = new javax.swing.JLabel();
        lbTongBuoi = new javax.swing.JLabel();
        txtTenLop = new javax.swing.JTextField();
        lbMaGV = new javax.swing.JLabel();
        lbMaLop = new javax.swing.JLabel();
        txtMaLop = new javax.swing.JTextField();
        cbxTrangThai = new javax.swing.JComboBox<>();
        lbTenLop = new javax.swing.JLabel();
        txtNgayKT = new javax.swing.JTextField();
        lbMaMH = new javax.swing.JLabel();
        txtTongBuoi = new javax.swing.JTextField();
        lbCaHoc = new javax.swing.JLabel();
        txtNgayBD = new javax.swing.JTextField();

        getContentPane().setLayout(null);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tblCTLop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Lớp", "Tên Lớp", "Mã GV", "Mã MH", "Mã Ca", "Tổng buổi", "Ngày BD", "Ngày KT", "Trạng thái"
            }
        ));
        tblCTLop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCTLopMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCTLop);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 180, 550, 120);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        btnDong.setText("Đóng");
        btnDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDongActionPerformed(evt);
            }
        });
        jPanel1.add(btnDong);
        btnDong.setBounds(380, 10, 100, 30);

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        jPanel1.add(btnThem);
        btnThem.setBounds(20, 10, 100, 30);

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        jPanel1.add(btnSua);
        btnSua.setBounds(140, 10, 100, 30);

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        jPanel1.add(btnXoa);
        btnXoa.setBounds(260, 10, 100, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(60, 320, 500, 50);

        lbNgayBD1.setText("Ngày KT:");
        getContentPane().add(lbNgayBD1);
        lbNgayBD1.setBounds(410, 130, 80, 30);
        getContentPane().add(txtMaMH);
        txtMaMH.setBounds(80, 130, 120, 30);
        getContentPane().add(txtMaGV);
        txtMaGV.setBounds(270, 130, 120, 30);
        getContentPane().add(txtCaHoc);
        txtCaHoc.setBounds(270, 50, 120, 30);

        lbTrangThai.setText("Trạng thái:");
        getContentPane().add(lbTrangThai);
        lbTrangThai.setBounds(410, 50, 80, 30);

        lbThongTinLopHoc.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbThongTinLopHoc.setText("THÔNG TIN LỚP HỌC");
        getContentPane().add(lbThongTinLopHoc);
        lbThongTinLopHoc.setBounds(190, 10, 300, 29);

        lbNgayBD.setText("Ngày BĐ:");
        getContentPane().add(lbNgayBD);
        lbNgayBD.setBounds(410, 90, 80, 30);

        lbTongBuoi.setText("Tổng buổi:");
        getContentPane().add(lbTongBuoi);
        lbTongBuoi.setBounds(210, 90, 70, 30);

        txtTenLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenLopActionPerformed(evt);
            }
        });
        getContentPane().add(txtTenLop);
        txtTenLop.setBounds(80, 90, 120, 30);

        lbMaGV.setText("Mã GV:");
        getContentPane().add(lbMaGV);
        lbMaGV.setBounds(210, 130, 70, 30);

        lbMaLop.setText("Mã lớp:");
        getContentPane().add(lbMaLop);
        lbMaLop.setBounds(10, 50, 70, 30);

        txtMaLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaLopActionPerformed(evt);
            }
        });
        getContentPane().add(txtMaLop);
        txtMaLop.setBounds(80, 50, 120, 30);

        cbxTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chọn", "Đắng Kí", "Đang học", "Tạm ngưng", "Hoàn Thành" }));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, cbxTrangThai, org.jdesktop.beansbinding.ELProperty.create("${selectedIndex}"), cbxTrangThai, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        cbxTrangThai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTrangThaiActionPerformed(evt);
            }
        });
        getContentPane().add(cbxTrangThai);
        cbxTrangThai.setBounds(490, 50, 120, 30);

        lbTenLop.setText("Tên lớp:");
        getContentPane().add(lbTenLop);
        lbTenLop.setBounds(10, 90, 70, 30);
        getContentPane().add(txtNgayKT);
        txtNgayKT.setBounds(490, 130, 120, 30);

        lbMaMH.setText("Mã MH:");
        getContentPane().add(lbMaMH);
        lbMaMH.setBounds(10, 130, 70, 30);
        getContentPane().add(txtTongBuoi);
        txtTongBuoi.setBounds(270, 90, 120, 30);

        lbCaHoc.setText("Ca học:");
        getContentPane().add(lbCaHoc);
        lbCaHoc.setBounds(210, 50, 70, 30);
        getContentPane().add(txtNgayBD);
        txtNgayBD.setBounds(490, 90, 120, 30);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblCTLopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCTLopMouseClicked
        // TODO add your handling code here:
        int row = tblCTLop.getSelectedRow();
        txtMaLop.setText((String)tblCTLop.getValueAt(row, 0));
        txtTenLop.setText((String)tblCTLop.getValueAt(row, 1));
        txtMaGV.setText((String)tblCTLop.getValueAt(row, 2));
        txtMaMH.setText((String)tblCTLop.getValueAt(row, 3));
        txtCaHoc.setText((String)tblCTLop.getValueAt(row, 4));
        txtTongBuoi.setText((String)tblCTLop.getValueAt(row, 5).toString());
        txtNgayBD.setText((String)tblCTLop.getValueAt(row, 6));
        txtNgayKT.setText((String)tblCTLop.getValueAt(row, 7));
        cbxTrangThai.getModel().setSelectedItem(tblCTLop.getValueAt(row, 8).toString());
        frmCTLopHoc lh = new frmCTLopHoc();
        JDesktopPane des = getDesktopPane();
        des.add(lh);
        lh.setVisible(true);
        
    }//GEN-LAST:event_tblCTLopMouseClicked

    private void txtMaLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaLopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaLopActionPerformed

    private void txtTenLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenLopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenLopActionPerformed

    private void btnDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDongActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnDongActionPerformed
    private void ShowData() {
        DefaultTableModel dtm = (DefaultTableModel)tblCTLop.getModel();
        dtm.setRowCount(0);
        frmCTLopDAO.ShowData(dtm);
        tblCTLop.setModel(dtm);
    }
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        if (frmCTLopDAO.KTTT(txtMaLop.getText()) == true) {
            JOptionPane.showMessageDialog(this, "Thêm lớp học thất bại","Thông báo",JOptionPane.INFORMATION_MESSAGE);
            ShowData();
        }
        else{
            String MaLop = txtMaLop.getText();
            String tenLop = txtTenLop.getText();
            String maMH = txtMaMH.getText();
            String maCa = txtCaHoc.getText();
            String maGV = txtMaGV.getText();
            String ngayBD = txtNgayBD.getText();
            String ngayKT = txtNgayKT.getText();
            String tongBuoi = txtTongBuoi.getText();
            String trangThai = cbxTrangThai.getSelectedItem().toString();
            pCTLop l = new pCTLop();
            l.setMaLop(MaLop);
            l.setTenLop(tenLop);
            l.setMaCa(maCa);
            l.setMaGV(maGV);
            l.setMaMH(maMH);
            l.setNgayBD(ngayBD);
            l.setNgayKT(ngayKT);
            l.setTongBuoi(Integer.parseInt(tongBuoi));
            l.setTrangThai(trangThai);
            boolean kq = frmCTLopDAO.themLop(l);
            if ( kq == true) {
                JOptionPane.showMessageDialog(this, "Thêm lớp học thành công","Thông báo",JOptionPane.INFORMATION_MESSAGE);
                ShowData();
            }
        }
    }//GEN-LAST:event_btnThemActionPerformed
    
    private void cbxTrangThaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTrangThaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxTrangThaiActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        String MaLop = txtMaLop.getText();
            String tenLop = txtTenLop.getText();
            String maMH = txtMaMH.getText();
            String maCa = txtCaHoc.getText();
            String maGV = txtMaGV.getText();
            String ngayBD = txtNgayBD.getText();
            String ngayKT = txtNgayKT.getText();
            String tongBuoi = txtTongBuoi.getText();
            String trangThai = cbxTrangThai.getSelectedItem().toString();
            pCTLop l = new pCTLop();
            l.setTenLop(tenLop);
            l.setMaCa(maCa);
            l.setMaGV(maGV);
            l.setMaMH(maMH);
            l.setNgayBD(ngayBD);
            l.setNgayKT(ngayKT);
//            l.setTongBuoi(tongBuoi);
            l.setTrangThai(trangThai);
            boolean kq = frmCTLopDAO.capNhatLop(MaLop, l);
            JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn cập nhật mã ]"+ txtMaLop.getText()+
                "]?","Xác nhận cập nhật", JOptionPane.YES_NO_OPTION);
            if ( kq == true) {
            JOptionPane.showMessageDialog(this, "Cập nhật thành công", "Thông báo",JOptionPane.INFORMATION_MESSAGE);
            ShowData();
            }
            else{
                JOptionPane.showMessageDialog(this, "Cập nhật không thành công", "Thông báo",JOptionPane.INFORMATION_MESSAGE);
            ShowData();
            }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        if (frmCTLopDAO.KTTT(txtMaLop.getText()) == false) {
            JOptionPane.showConfirmDialog(null, "Mã ko tồn tại!");
            return;
        }
        else{
            if (frmCTLopDAO.xoaLop(txtMaLop.getText()) == true) {
                JOptionPane.showConfirmDialog(null, "Xóa thành công!");
                ShowData();
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed
   
        public void set_data()
    {

            JCheckBox check=new JCheckBox();
            JComboBox com=new JComboBox();
            com.addItem("Sinh viên");
            com.addItem("Giáo Viên");
            com.addItem("Học sinh");
            com.addItem("Nhân viên văn phòng");
            com.addItem("Khác");
            DefaultCellEditor de=new DefaultCellEditor(check);
            DefaultCellEditor de2=new DefaultCellEditor(com);
            tblCTLop.getColumnModel().getColumn(1).setCellEditor(de);
            tblCTLop.getColumnModel().getColumn(2).setCellEditor(de2);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDong;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbxTrangThai;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCaHoc;
    private javax.swing.JLabel lbMaGV;
    private javax.swing.JLabel lbMaLop;
    private javax.swing.JLabel lbMaMH;
    private javax.swing.JLabel lbNgayBD;
    private javax.swing.JLabel lbNgayBD1;
    private javax.swing.JLabel lbTenLop;
    private javax.swing.JLabel lbThongTinLopHoc;
    private javax.swing.JLabel lbTongBuoi;
    private javax.swing.JLabel lbTrangThai;
    private javax.swing.JTable tblCTLop;
    private javax.swing.JTextField txtCaHoc;
    private javax.swing.JTextField txtMaGV;
    private javax.swing.JTextField txtMaLop;
    private javax.swing.JTextField txtMaMH;
    private javax.swing.JTextField txtNgayBD;
    private javax.swing.JTextField txtNgayKT;
    private javax.swing.JTextField txtTenLop;
    private javax.swing.JTextField txtTongBuoi;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
