/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlttgs;

import dao.frmCTDiemDanhDAO;
import java.awt.List;
import java.sql.PreparedStatement;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pojo.pCTDiemDanh;
import pojo.pDiemDanh;

/**
 *
 * @author Admin
 */
public class frmCTDiemDanh extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmCTLopHoc
     */
    public frmCTDiemDanh() {
        initComponents();
        this.setLocation(60,60);
        this.setSize(655, 430);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        ShowData1();
        ShowData2();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCTLop = new javax.swing.JTable();
        lbThongTinLopHoc = new javax.swing.JLabel();
        lbMaLop = new javax.swing.JLabel();
        txtMaLop = new javax.swing.JTextField();
        lbTenLop = new javax.swing.JLabel();
        txtTenHV = new javax.swing.JTextField();
        lbSoBuoiDaHoc = new javax.swing.JLabel();
        txtSoBuoiDaHoc = new javax.swing.JTextField();
        lbTongBuoi = new javax.swing.JLabel();
        txtTongBuoi = new javax.swing.JTextField();
        btnDong = new javax.swing.JButton();

        getContentPane().setLayout(null);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tblCTLop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Ngày CheckOut", "Ngày CheckIn", "TT CheckIn", "TT CheckOut"
            }
        ));
        tblCTLop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCTLopMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCTLop);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 190, 550, 120);

        lbThongTinLopHoc.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbThongTinLopHoc.setText("THÔNG TIN ĐIỂM DANH");
        getContentPane().add(lbThongTinLopHoc);
        lbThongTinLopHoc.setBounds(150, 10, 300, 29);

        lbMaLop.setText("Mã lớp:");
        getContentPane().add(lbMaLop);
        lbMaLop.setBounds(20, 50, 43, 16);

        txtMaLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaLopActionPerformed(evt);
            }
        });
        getContentPane().add(txtMaLop);
        txtMaLop.setBounds(90, 50, 98, 22);

        lbTenLop.setText("Tên HV:");
        getContentPane().add(lbTenLop);
        lbTenLop.setBounds(20, 80, 47, 16);

        txtTenHV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenHVActionPerformed(evt);
            }
        });
        getContentPane().add(txtTenHV);
        txtTenHV.setBounds(90, 80, 98, 22);

        lbSoBuoiDaHoc.setText("Số BDH:");
        getContentPane().add(lbSoBuoiDaHoc);
        lbSoBuoiDaHoc.setBounds(290, 80, 47, 16);
        getContentPane().add(txtSoBuoiDaHoc);
        txtSoBuoiDaHoc.setBounds(370, 80, 98, 22);

        lbTongBuoi.setText("Số BDN:");
        getContentPane().add(lbTongBuoi);
        lbTongBuoi.setBounds(280, 50, 47, 16);
        getContentPane().add(txtTongBuoi);
        txtTongBuoi.setBounds(370, 50, 98, 22);

        btnDong.setText("Đóng");
        btnDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDongActionPerformed(evt);
            }
        });
        getContentPane().add(btnDong);
        btnDong.setBounds(100, 330, 350, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblCTLopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCTLopMouseClicked
        // TODO add your handling code here:
//        int row = tblCTLop.getSelectedRow();
//        txtMaLop.setText((String)tblCTLop.getValueAt(row, row));
//        txtTenHV.setText((String)tblCTLop.getValueAt(row, row));
//        txtTongBuoi.setText((String)tblCTLop.getValueAt(row, row));
//        txtSoBuoiDaHoc.setText((String)tblCTLop.getValueAt(row, row));
    }//GEN-LAST:event_tblCTLopMouseClicked

    private void txtMaLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaLopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaLopActionPerformed

    private void txtTenHVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenHVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenHVActionPerformed

    private void btnDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDongActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnDongActionPerformed
    private void ShowData1() {
        ArrayList<pDiemDanh> dsDD = dao.frmDiemDanhDAO.LoadData();
        txtMaLop.getText();
        txtTenHV.getText();
        txtTongBuoi.getText();
        txtSoBuoiDaHoc.getText();
    }   
    private void ShowData2() {
        ArrayList<pCTDiemDanh> dsDD = dao.frmCTDiemDanhDAO.LoadData();
        DefaultTableModel dtm = (DefaultTableModel)tblCTLop.getModel();
        dtm.setRowCount(0);
        frmCTDiemDanhDAO.ShowData2(dtm);
        tblCTLop.setModel(dtm);
    }   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDong;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbMaLop;
    private javax.swing.JLabel lbSoBuoiDaHoc;
    private javax.swing.JLabel lbTenLop;
    private javax.swing.JLabel lbThongTinLopHoc;
    private javax.swing.JLabel lbTongBuoi;
    private javax.swing.JTable tblCTLop;
    private javax.swing.JTextField txtMaLop;
    private javax.swing.JTextField txtSoBuoiDaHoc;
    private javax.swing.JTextField txtTenHV;
    private javax.swing.JTextField txtTongBuoi;
    // End of variables declaration//GEN-END:variables
}
