/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlttgs;

import dao.frmDangKiDAO;
import javax.swing.JOptionPane;
import pojo.pNguoiDung;

/**
 *
 * @author hiepg
 */
public class frmDangKi extends javax.swing.JDialog {

    /**
     * Creates new form frmDangKi
     */
    public frmDangKi(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setSize(420, 300);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtMaND = new javax.swing.JTextField();
        lbTenDangNhap = new javax.swing.JLabel();
        lbMatKhau = new javax.swing.JLabel();
        txtMatKhau = new javax.swing.JPasswordField();
        txtTenND = new javax.swing.JTextField();
        lbTenDangNhap1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnDangKi = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(txtMaND);
        txtMaND.setBounds(180, 70, 170, 30);

        lbTenDangNhap.setText("Tên đăng nhập:");
        getContentPane().add(lbTenDangNhap);
        lbTenDangNhap.setBounds(60, 70, 110, 30);

        lbMatKhau.setText("Mật khẩu:");
        getContentPane().add(lbMatKhau);
        lbMatKhau.setBounds(60, 150, 110, 30);
        getContentPane().add(txtMatKhau);
        txtMatKhau.setBounds(180, 150, 170, 30);
        getContentPane().add(txtTenND);
        txtTenND.setBounds(180, 110, 170, 30);

        lbTenDangNhap1.setText("Tên Người Dùng:");
        getContentPane().add(lbTenDangNhap1);
        lbTenDangNhap1.setBounds(60, 110, 110, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("ĐĂNG KÍ THÀNH VIÊN");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 20, 240, 40);

        btnDangKi.setText("Register");
        btnDangKi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangKiActionPerformed(evt);
            }
        });
        getContentPane().add(btnDangKi);
        btnDangKi.setBounds(80, 190, 100, 30);

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel);
        btnCancel.setBounds(220, 190, 100, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnDangKiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangKiActionPerformed
        // TODO add your handling code here:
        String ma = txtMaND.getText();
        if (frmDangKiDAO.KTTT(ma) == true) {
            JOptionPane.showConfirmDialog(null, "Mã người dùng đã được sử dụng!", "Thông báo!", JOptionPane.OK_CANCEL_OPTION);
            txtMaND.setText("");
            txtTenND.setText("");
            txtMatKhau.setText("");
            return;
        }
        else
        {
            String ten = txtTenND.getText();
            String mk = txtMatKhau.getText();
            pNguoiDung nd = new pNguoiDung();
            nd.setMaND(ma);
            nd.setTenND(ten);
            nd.setMatKhau(mk);
            if (frmDangKiDAO.Add(nd) == true) {
                JOptionPane.showConfirmDialog(null, "Đăng Kí Thành Công!", "Thông báo!", JOptionPane.OK_CANCEL_OPTION);
                txtMaND.setText("");
                txtTenND.setText("");
                txtMatKhau.setText("");
                return;
            }
        }
    }//GEN-LAST:event_btnDangKiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDangKi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDangKi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDangKi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDangKi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmDangKi dialog = new frmDangKi(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDangKi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbMatKhau;
    private javax.swing.JLabel lbTenDangNhap;
    private javax.swing.JLabel lbTenDangNhap1;
    private javax.swing.JTextField txtMaND;
    private javax.swing.JPasswordField txtMatKhau;
    private javax.swing.JTextField txtTenND;
    // End of variables declaration//GEN-END:variables
}
