/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlttgs;

import dao.frmDMKDAO;
import javax.swing.JOptionPane;
import pojo.pNguoiDung;

/**
 *
 * @author hiepg
 */
public class frmDoiMK extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmDoiMK
     */
    public frmDoiMK() {
        initComponents();
        initComponents();
        this.setSize(420, 300);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        btnDoi = new javax.swing.JButton();
        btnDong = new javax.swing.JButton();
        txtMK = new javax.swing.JPasswordField();
        txtMKM = new javax.swing.JPasswordField();
        txtNhapLai = new javax.swing.JPasswordField();

        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("ĐỔI MẬT KHẨU");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 10, 180, 30);

        jLabel2.setText("Tên DN:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 60, 80, 30);

        jLabel3.setText("Mật Khẩu:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 100, 80, 30);

        jLabel4.setText("Mật Khẩu mới:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 140, 80, 30);

        jLabel5.setText("Nhập lại:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 180, 80, 30);
        getContentPane().add(txtTen);
        txtTen.setBounds(110, 60, 220, 30);

        btnDoi.setText("Đổi Mật Khẩu");
        btnDoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoiActionPerformed(evt);
            }
        });
        getContentPane().add(btnDoi);
        btnDoi.setBounds(70, 220, 100, 40);

        btnDong.setText("Đóng");
        getContentPane().add(btnDong);
        btnDong.setBounds(200, 220, 100, 40);
        getContentPane().add(txtMK);
        txtMK.setBounds(110, 100, 220, 30);
        getContentPane().add(txtMKM);
        txtMKM.setBounds(110, 140, 220, 30);
        getContentPane().add(txtNhapLai);
        txtNhapLai.setBounds(110, 180, 220, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoiActionPerformed
        // TODO add your handling code here:
        if (frmDMKDAO.KTTT(txtTen.getText()) == false) {
            JOptionPane.showMessageDialog(null, "Không có tài khoản này!");
            return;
        } else {
            if (frmDMKDAO.KTMK(txtTen.getText(), txtMK.getText()) == true) {
                if (txtMKM.getText() == txtNhapLai.getText()) {
                    pNguoiDung mh = new pNguoiDung();
                    mh.setMatKhau(txtMKM.getText());
                    if (frmDMKDAO.Update(txtTen.getText(), mh) == true) {
                        JOptionPane.showMessageDialog(null, "Đổi mật khẩu thành công!");
                        this.dispose();
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Nhập lại mật khẩu không đúng. Vui lòng nhập lại!");
                    txtNhapLai.setText("");
                    txtNhapLai.requestFocus();
                    return;
                }
            } else {
                JOptionPane.showMessageDialog(null, "Mật khẩu không đúng. Vui lòng nhập lại!");
                txtNhapLai.setText("");
                txtNhapLai.requestFocus();
                return;
            }

        }
    }//GEN-LAST:event_btnDoiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoi;
    private javax.swing.JButton btnDong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField txtMK;
    private javax.swing.JPasswordField txtMKM;
    private javax.swing.JPasswordField txtNhapLai;
    private javax.swing.JTextField txtTen;
    // End of variables declaration//GEN-END:variables
}
