/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlttgs;

import dao.frmDangKy;
import java.awt.Color;
import java.sql.Connection;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pojo.DangKyHoc;


/**
 *
 * @author phamnhutquy
 */
public class frmDangKyHoc extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmDangKyHoc
     */
    public frmDangKyHoc() {
        initComponents();
        this.setLocation(50,30);
        this.setSize(540, 300);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
    }
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMaDK = new javax.swing.JTextField();
        txtMaHV = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNgayDangKy = new javax.swing.JTextField();
        txtHocPhi = new javax.swing.JTextField();
        btnNhapMoi = new javax.swing.JButton();
        btnDangKy = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtMaLichDay = new javax.swing.JTextField();

        setTitle("Đăng Ký Học");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("THÔNG TIN ĐĂNG KÝ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, 20, 191, 49);

        jLabel2.setText("Mã đăng ký:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(19, 70, 80, 30);

        jLabel3.setText("Mã học viên:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(170, 150, 90, 30);
        getContentPane().add(txtMaDK);
        txtMaDK.setBounds(100, 70, 117, 30);
        getContentPane().add(txtMaHV);
        txtMaHV.setBounds(260, 150, 117, 30);

        jLabel8.setText("Ngày đăng ký:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(250, 70, 90, 30);

        jLabel9.setText("Học phí:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(250, 110, 90, 30);
        getContentPane().add(txtNgayDangKy);
        txtNgayDangKy.setBounds(340, 70, 123, 30);
        getContentPane().add(txtHocPhi);
        txtHocPhi.setBounds(340, 110, 123, 30);

        btnNhapMoi.setText("Nhập mới");
        btnNhapMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapMoiActionPerformed(evt);
            }
        });
        getContentPane().add(btnNhapMoi);
        btnNhapMoi.setBounds(100, 190, 100, 40);

        btnDangKy.setText("Đăng ký");
        btnDangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangKyActionPerformed(evt);
            }
        });
        getContentPane().add(btnDangKy);
        btnDangKy.setBounds(220, 190, 90, 40);

        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        getContentPane().add(btnThoat);
        btnThoat.setBounds(330, 190, 110, 40);

        jLabel10.setText("Mã lớp học:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(20, 110, 80, 30);
        getContentPane().add(txtMaLichDay);
        txtMaLichDay.setBounds(100, 110, 117, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangKyActionPerformed
        // TODO add your handling code here:
        if(frmDangKy.KTTT(txtMaDK.getText())== false)
        {
            String MaDK = txtMaDK.getText();
            String MaHV = txtMaHV.getText();
            String MaLichDay = txtMaLichDay.getText();
            String NgayDangKy = txtNgayDangKy.getText();
            int HocPhi = Integer.parseInt(txtHocPhi.getText());
            DangKyHoc dk = new DangKyHoc();
            dk.setMaDK(MaDK);
            dk.setMaHV(MaHV);
            dk.setMaLichDay(MaLichDay);
            dk.setNgayDangKy(NgayDangKy);
            dk.setHocPhi(HocPhi);
            boolean kq = frmDangKy.themDangKy(dk);
            if(kq==true)
            {
                JOptionPane.showMessageDialog(this, "Đăng ký thành công","Thông báo",JOptionPane.INFORMATION_MESSAGE);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Mã đăng ký đã tồn tại!","Thông báo",JOptionPane.OK_OPTION);
            return;
        }
    }//GEN-LAST:event_btnDangKyActionPerformed

    private void btnNhapMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapMoiActionPerformed
        // TODO add your handling code here:
        txtMaDK.setText("");
        txtMaHV.setText("");
        txtMaLichDay.setText("");
        txtNgayDangKy.setText("");
        txtHocPhi.setText("");
        txtMaDK.requestFocus();
    }//GEN-LAST:event_btnNhapMoiActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnThoatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangKy;
    private javax.swing.JButton btnNhapMoi;
    private javax.swing.JButton btnThoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtHocPhi;
    private javax.swing.JTextField txtMaDK;
    private javax.swing.JTextField txtMaHV;
    private javax.swing.JTextField txtMaLichDay;
    private javax.swing.JTextField txtNgayDangKy;
    // End of variables declaration//GEN-END:variables
}
