/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlttgs;

import dao.frmCTDiemDanhDAO;
import dao.frmCTLopDAO;
import java.util.ArrayList;
import javax.swing.DefaultCellEditor;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;
import pojo.pDiemDanh;
import pojo.pCTLop;

/**
 *
 * @author Admin
 */
public class frmDiemDanh extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmCTLopHoc
     */
    public frmDiemDanh() {
        initComponents();
        this.setLocation(60,60);
        this.setSize(655, 430);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        ShowDT1();
        ShowDT2();
        set_data();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCTLop = new javax.swing.JTable();
        lbThongTinLopHoc = new javax.swing.JLabel();
        lbMaLop = new javax.swing.JLabel();
        txtMaLop = new javax.swing.JTextField();
        lbTenLop = new javax.swing.JLabel();
        txtTenLop = new javax.swing.JTextField();
        lbMaMH = new javax.swing.JLabel();
        lbCaHoc = new javax.swing.JLabel();
        lbSoBuoiDaHoc = new javax.swing.JLabel();
        txtNgayKT = new javax.swing.JTextField();
        lbMaGV = new javax.swing.JLabel();
        lbNgayBD = new javax.swing.JLabel();
        txtNgayBD = new javax.swing.JTextField();
        lbTrangThai = new javax.swing.JLabel();
        cbxMaMH = new javax.swing.JComboBox<>();
        lbTongBuoi = new javax.swing.JLabel();
        txtTongBuoi = new javax.swing.JTextField();
        cbxTrangThai = new javax.swing.JComboBox<>();
        cbxMaCa = new javax.swing.JComboBox<>();
        cbxMaGV = new javax.swing.JComboBox<>();
        btnDiemDanh = new javax.swing.JButton();

        getContentPane().setLayout(null);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tblCTLop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã HV", "Tên HV", "Số buổi đã học", "Số buổi nghỉ", "Trạng thái HV", "CheckIn", "CheckOut"
            }
        ));
        tblCTLop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCTLopMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCTLop);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 160, 540, 120);

        lbThongTinLopHoc.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbThongTinLopHoc.setText("THÔNG TIN ĐIỂM DANH");
        getContentPane().add(lbThongTinLopHoc);
        lbThongTinLopHoc.setBounds(130, 10, 300, 29);

        lbMaLop.setText("Mã lớp:");
        getContentPane().add(lbMaLop);
        lbMaLop.setBounds(20, 50, 43, 16);

        txtMaLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaLopActionPerformed(evt);
            }
        });
        getContentPane().add(txtMaLop);
        txtMaLop.setBounds(90, 50, 98, 22);

        lbTenLop.setText("Tên lớp:");
        getContentPane().add(lbTenLop);
        lbTenLop.setBounds(20, 80, 48, 16);

        txtTenLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenLopActionPerformed(evt);
            }
        });
        getContentPane().add(txtTenLop);
        txtTenLop.setBounds(90, 80, 98, 22);

        lbMaMH.setText("Mã MH:");
        getContentPane().add(lbMaMH);
        lbMaMH.setBounds(20, 110, 44, 16);

        lbCaHoc.setText("Ca học:");
        getContentPane().add(lbCaHoc);
        lbCaHoc.setBounds(200, 50, 44, 16);

        lbSoBuoiDaHoc.setText("Ngày KT:");
        getContentPane().add(lbSoBuoiDaHoc);
        lbSoBuoiDaHoc.setBounds(200, 80, 60, 16);
        getContentPane().add(txtNgayKT);
        txtNgayKT.setBounds(270, 80, 98, 22);

        lbMaGV.setText("Mã GV:");
        getContentPane().add(lbMaGV);
        lbMaGV.setBounds(200, 110, 42, 16);

        lbNgayBD.setText("Ngày BĐ:");
        getContentPane().add(lbNgayBD);
        lbNgayBD.setBounds(380, 50, 70, 16);
        getContentPane().add(txtNgayBD);
        txtNgayBD.setBounds(450, 50, 98, 22);

        lbTrangThai.setText("Trạng thái:");
        getContentPane().add(lbTrangThai);
        lbTrangThai.setBounds(380, 110, 70, 16);

        cbxMaMH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cbxMaMH);
        cbxMaMH.setBounds(90, 110, 100, 22);

        lbTongBuoi.setText("Tổng buổi:");
        getContentPane().add(lbTongBuoi);
        lbTongBuoi.setBounds(380, 80, 62, 16);
        getContentPane().add(txtTongBuoi);
        txtTongBuoi.setBounds(450, 80, 98, 22);

        cbxTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cbxTrangThai);
        cbxTrangThai.setBounds(450, 110, 100, 22);

        cbxMaCa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cbxMaCa);
        cbxMaCa.setBounds(270, 50, 100, 22);

        cbxMaGV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cbxMaGV);
        cbxMaGV.setBounds(270, 110, 100, 22);

        btnDiemDanh.setText("Điểm danh");
        btnDiemDanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiemDanhActionPerformed(evt);
            }
        });
        getContentPane().add(btnDiemDanh);
        btnDiemDanh.setBounds(190, 290, 150, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblCTLopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCTLopMouseClicked
        // TODO add your handling code here:
//        int row = tblCTLop.getSelectedRow();
//        txtMa.setText((String)tblCTLop.getValueAt(row, 0));
//        txtTenLop.setText((String)tblCTLop.getValueAt(row, 1));
//        txtLoai.setText((String)tblCTLop.getValueAt(row, 2));
//        txtGioiTinh.setText((String)tblCTLop.getValueAt(row, 3) + "");
    }//GEN-LAST:event_tblCTLopMouseClicked

    private void txtMaLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaLopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaLopActionPerformed

    private void txtTenLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenLopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenLopActionPerformed

    private void btnDiemDanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiemDanhActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnDiemDanhActionPerformed
    private void ShowDT1() {
        ArrayList<pDiemDanh> dsDD = dao.frmDiemDanhDAO.LoadData();
        DefaultTableModel dtm = (DefaultTableModel)tblCTLop.getModel();
        dtm.setRowCount(0);
        frmCTDiemDanhDAO.ShowData2(dtm);
        tblCTLop.setModel(dtm);
    }  
    private void ShowDT2() {
        ArrayList<pCTLop> dsLop = dao.frmCTLopDAO.LoadData();
        txtMaLop.getText();
        txtTenLop.getText();
        txtTongBuoi.getText();
        cbxMaCa.getModel().getSelectedItem().toString();
        cbxMaGV.getModel().getSelectedItem().toString();
        cbxMaMH.getModel().getSelectedItem().toString();
        txtNgayBD.getText();
        txtNgayKT.getText();
        cbxTrangThai.getModel().getSelectedItem().toString();
    } 
    public void set_data()
    {
        JCheckBox check=new JCheckBox();
        DefaultCellEditor de=new DefaultCellEditor(check);
        tblCTLop.getColumnModel().getColumn(1).setCellEditor(de);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDiemDanh;
    private javax.swing.JComboBox<String> cbxMaCa;
    private javax.swing.JComboBox<String> cbxMaGV;
    private javax.swing.JComboBox<String> cbxMaMH;
    private javax.swing.JComboBox<String> cbxTrangThai;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCaHoc;
    private javax.swing.JLabel lbMaGV;
    private javax.swing.JLabel lbMaLop;
    private javax.swing.JLabel lbMaMH;
    private javax.swing.JLabel lbNgayBD;
    private javax.swing.JLabel lbSoBuoiDaHoc;
    private javax.swing.JLabel lbTenLop;
    private javax.swing.JLabel lbThongTinLopHoc;
    private javax.swing.JLabel lbTongBuoi;
    private javax.swing.JLabel lbTrangThai;
    private javax.swing.JTable tblCTLop;
    private javax.swing.JTextField txtMaLop;
    private javax.swing.JTextField txtNgayBD;
    private javax.swing.JTextField txtNgayKT;
    private javax.swing.JTextField txtTenLop;
    private javax.swing.JTextField txtTongBuoi;
    // End of variables declaration//GEN-END:variables
}
