/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlttgs;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class frmDangNhap extends javax.swing.JDialog {

    private String strTenDangNhap;
    private String strMatKhau;
    private String strTenNguoiDung;
    private boolean bKetQuaDangNhap;

    /**
     * Creates new form frmDangNhap
     */
    public frmDangNhap(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setSize(420, 300);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbDangNhap = new javax.swing.JLabel();
        lbTenDangNhap = new javax.swing.JLabel();
        txtTenDangNhap = new javax.swing.JTextField();
        lbMatKhau = new javax.swing.JLabel();
        txtMatKhau = new javax.swing.JPasswordField();
        btDangNhap = new javax.swing.JButton();
        btThoat = new javax.swing.JButton();
        btnDangKi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        lbDangNhap.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbDangNhap.setText("ĐĂNG NHẬP");
        getContentPane().add(lbDangNhap);
        lbDangNhap.setBounds(110, 20, 148, 29);

        lbTenDangNhap.setText("User:");
        getContentPane().add(lbTenDangNhap);
        lbTenDangNhap.setBounds(60, 70, 70, 30);
        getContentPane().add(txtTenDangNhap);
        txtTenDangNhap.setBounds(130, 70, 200, 30);

        lbMatKhau.setText("Password:");
        getContentPane().add(lbMatKhau);
        lbMatKhau.setBounds(60, 110, 70, 30);
        getContentPane().add(txtMatKhau);
        txtMatKhau.setBounds(130, 110, 200, 30);

        btDangNhap.setText("Log in");
        btDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDangNhapActionPerformed(evt);
            }
        });
        getContentPane().add(btDangNhap);
        btDangNhap.setBounds(70, 160, 70, 31);

        btThoat.setText("Cancel");
        btThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThoatActionPerformed(evt);
            }
        });
        getContentPane().add(btThoat);
        btThoat.setBounds(250, 160, 70, 31);

        btnDangKi.setText("Register");
        btnDangKi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangKiActionPerformed(evt);
            }
        });
        getContentPane().add(btnDangKi);
        btnDangKi.setBounds(150, 160, 90, 31);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDangNhapActionPerformed
//        // TODO add your handling code here:
        String strServer = "DESKTOP-95UDENR\\SQLEXPRESS";
        String strDatabase = "Java";
        String user = "sa";
        String pass = "sa";
        Connection connection = null;
        Statement statement = null;
        ResultSet result = null;
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String connectionURL = "jdbc:sqlserver://" + strServer
                    + ":1433;databaseName = " + strDatabase
                    //                    + ";integratedSecurity = true";
                    + ";User = " + user
                    + ";Password = " + pass;
            connection = DriverManager.getConnection(connectionURL);
            statement = connection.createStatement();
            String sql = "Select * from NguoiDung where"
                    + " MaND = '" + txtTenDangNhap.getText() + "'"
                    + " and MatKhau = '" + txtMatKhau.getText() + "'";
            result = statement.executeQuery(sql);
            while (result.next()) {
                strTenDangNhap = result.getString("MaND");
                strMatKhau = result.getString("MatKhau");
                strTenNguoiDung = result.getString("TenND");
                bKetQuaDangNhap = true;
            }
            connection.close();
            if (bKetQuaDangNhap) {
                JOptionPane.showMessageDialog(this, "Đăng Nhập Thành Công!");
                this.setVisible(false);
//                QLTTGS ql = new QLTTGS();
//                ql.setVisible(true);
//                ql.mnuDangNhap.setEnabled(false);
//                this.mnuDangXuat.setEnabled(true);
//                this.mnQuanLy.setEnabled(true);
//                this.mnDangKi.setEnabled(true);
//                this.mnAdmin.setEnabled(true);
//                this.mnuDoiMatKhau.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(this, "Tên đăng nhập hoặc mật khẩu không đúng!");
                txtTenDangNhap.requestFocus();
                txtTenDangNhap.setText("");
                txtMatKhau.setText("");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_btDangNhapActionPerformed

    private void btnDangKiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangKiActionPerformed
        // TODO add your handling code here:
        frmDangKi dk = new frmDangKi(null, true);
        dk.setVisible(true);
    }//GEN-LAST:event_btnDangKiActionPerformed

    private void btThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThoatActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btThoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmDangNhap dialog = new frmDangNhap(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDangNhap;
    private javax.swing.JButton btThoat;
    private javax.swing.JButton btnDangKi;
    private javax.swing.JLabel lbDangNhap;
    private javax.swing.JLabel lbMatKhau;
    private javax.swing.JLabel lbTenDangNhap;
    private javax.swing.JPasswordField txtMatKhau;
    private javax.swing.JTextField txtTenDangNhap;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the strTenDangNhap
     */
    public String getStrTenDangNhap() {
        return strTenDangNhap;
    }

    /**
     * @param strTenDangNhap the strTenDangNhap to set
     */
    public void setStrTenDangNhap(String strTenDangNhap) {
        this.strTenDangNhap = strTenDangNhap;
    }

    /**
     * @return the strMatKhau
     */
    public String getStrMatKhau() {
        return strMatKhau;
    }

    /**
     * @param strMatKhau the strMatKhau to set
     */
    public void setStrMatKhau(String strMatKhau) {
        this.strMatKhau = strMatKhau;
    }

    /**
     * @return the strTenNguoiDung
     */
    public String getStrTenNguoiDung() {
        return strTenNguoiDung;
    }

    /**
     * @param strTenNguoiDung the strTenNguoiDung to set
     */
    public void setStrTenNguoiDung(String strTenNguoiDung) {
        this.strTenNguoiDung = strTenNguoiDung;
    }

    /**
     * @return the bKetQuaDangNhap
     */
    public boolean isbKetQuaDangNhap() {
        return bKetQuaDangNhap;
    }

    /**
     * @param bKetQuaDangNhap the bKetQuaDangNhap to set
     */
    public void setbKetQuaDangNhap(boolean bKetQuaDangNhap) {
        this.bKetQuaDangNhap = bKetQuaDangNhap;
    }

    boolean getbKetQuaDangNhap() {
        return bKetQuaDangNhap;
    }
}
