/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlttgs;

import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JDesktopPane;
import javax.swing.table.DefaultTableModel;
import pojo.pCTGiangVien;

/**
 *
 * @author Admin
 */
public class frmGiaSu extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmCTGiaSu
     */
    public frmGiaSu() {
        initComponents();
        this.setLocation(60,60);
        this.setSize(655, 430);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        ShowData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblTTGV = new javax.swing.JTable();
        lbThongTinGiangVien = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnQuanLi = new javax.swing.JButton();
        btnDong = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();

        getContentPane().setLayout(null);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tblTTGV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Gia Sư", "Tên Gia Sư", "Ngày Sinh", "Giới Tính", "Điện Thoại", "Địa Chỉ", "Môn Học"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTTGV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTTGVMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTTGV);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 50, 600, 170);

        lbThongTinGiangVien.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbThongTinGiangVien.setText("THÔNG TIN GIẢNG VIÊN");
        getContentPane().add(lbThongTinGiangVien);
        lbThongTinGiangVien.setBounds(190, 10, 300, 29);

        jPanel1.setLayout(null);

        btnQuanLi.setText("Quản Lí");
        btnQuanLi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLiActionPerformed(evt);
            }
        });
        jPanel1.add(btnQuanLi);
        btnQuanLi.setBounds(190, 60, 120, 40);

        btnDong.setText("Đóng");
        btnDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDongActionPerformed(evt);
            }
        });
        jPanel1.add(btnDong);
        btnDong.setBounds(360, 60, 120, 40);

        btnTimKiem.setText("Tìm kiếm");
        jPanel1.add(btnTimKiem);
        btnTimKiem.setBounds(20, 60, 120, 40);

        jLabel1.setText("Tên GS: ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 10, 80, 30);
        jPanel1.add(txtTimKiem);
        txtTimKiem.setBounds(130, 10, 310, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(70, 240, 500, 120);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblTTGVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTTGVMouseClicked
        // TODO add your handling code here:
//        int row = tblTTGV.getSelectedRow();
//        txtMa.setText((String)tblTTGV.getValueAt(row, 0));
//        txtTenGV.setText((String)tblTTGV.getValueAt(row, 1));
//        txtLoai.setText((String)tblTTGV.getValueAt(row, 2));
//        txtGioiTinh.setText((String)tblTTGV.getValueAt(row, 3) + "");
    }//GEN-LAST:event_tblTTGVMouseClicked

    private void btnQuanLiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLiActionPerformed
        // TODO add your handling code here:
        frmCTGiaSu gs = new frmCTGiaSu();
        JDesktopPane des = getDesktopPane();
        des.add(gs);
        gs.setVisible(true);
    }//GEN-LAST:event_btnQuanLiActionPerformed

    private void btnDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDongActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnDongActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDong;
    private javax.swing.JButton btnQuanLi;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbThongTinGiangVien;
    private javax.swing.JTable tblTTGV;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables

    private void ShowData() {
        ArrayList<pCTGiangVien> dsGV = dao.frmCTGiaSuDAO.LoadData();
        DefaultTableModel dtmGV = (DefaultTableModel)tblTTGV.getModel();
        dtmGV.setRowCount(0);
        for (pCTGiangVien giangVien : dsGV) {
            Vector<Object> vec = new Vector<Object>();
            vec.add(giangVien.getMaGS());
            vec.add(giangVien.getTenGS());
            vec.add(giangVien.getNgaySinh());
            vec.add(giangVien.getGioiTinh());
            vec.add(giangVien.getDienThoai());
            vec.add(giangVien.getDiaChi());
            vec.add(giangVien.getMonHoc());
            dtmGV.addRow(vec);
        }
        tblTTGV.setModel(dtmGV);
    }
}
