/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlttgs;

import dao.frmCTMonHocDAO;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JDesktopPane;
import javax.swing.table.DefaultTableModel;
import pojo.pCTHocVien;
import pojo.pCTMonHoc;

/**
 *
 * @author Admin
 */
public class frmMonHoc extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmMonHoc
     */
    public frmMonHoc() {
        initComponents();
        this.setLocation(60,60);
        this.setSize(655, 430);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        ShowData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDSMH = new javax.swing.JTable();
        lbThongTinLopHoc = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnQuanLi = new javax.swing.JButton();
        btnDong = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        btnRef = new javax.swing.JButton();

        getContentPane().setLayout(null);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tblDSMH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã môn", "Tên Môn học", "Mã lớp", "Mã GV", "Ca", "Ngày bắt đầu", "Số buổi đã học", "Tổng buổi", "Trạng thái"
            }
        ));
        tblDSMH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDSMHMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDSMH);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 50, 660, 190);

        lbThongTinLopHoc.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbThongTinLopHoc.setText("DANH SÁCH MÔN HỌC");
        getContentPane().add(lbThongTinLopHoc);
        lbThongTinLopHoc.setBounds(210, 10, 300, 29);

        jPanel1.setLayout(null);

        btnQuanLi.setText("Quản Lí");
        btnQuanLi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLiActionPerformed(evt);
            }
        });
        jPanel1.add(btnQuanLi);
        btnQuanLi.setBounds(190, 60, 120, 40);

        btnDong.setText("Đóng");
        btnDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDongActionPerformed(evt);
            }
        });
        jPanel1.add(btnDong);
        btnDong.setBounds(360, 60, 120, 40);

        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });
        jPanel1.add(btnTimKiem);
        btnTimKiem.setBounds(20, 60, 120, 40);

        jLabel1.setText("Tên Môn học:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 10, 80, 30);
        jPanel1.add(txtTimKiem);
        txtTimKiem.setBounds(130, 10, 310, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(70, 290, 500, 120);

        btnRef.setText("Refresh");
        btnRef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefActionPerformed(evt);
            }
        });
        getContentPane().add(btnRef);
        btnRef.setBounds(273, 250, 100, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblDSMHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDSMHMouseClicked
//        // TODO add your handling code here:
//        int row = tblThongTinHV.getSelectedRow();
//        txtMa.setText((String)tblThongTinHV.getValueAt(row, 0));
//        txtTenMH.setText((String)tblThongTinHV.getValueAt(row, 1));
//        txtLoai.setText((String)tblThongTinHV.getValueAt(row, 2));
//        txtGioiTinh.setText((String)tblThongTinHV.getValueAt(row, 3) + "");
    }//GEN-LAST:event_tblDSMHMouseClicked

    private void btnQuanLiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLiActionPerformed
        // TODO add your handling code here:
        frmCTMonHoc mh = new frmCTMonHoc();
        JDesktopPane des = getDesktopPane();
        des.add(mh);
        mh.setVisible(true);
    }//GEN-LAST:event_btnQuanLiActionPerformed

    private void btnDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDongActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnDongActionPerformed

    private void btnRefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel)tblDSMH.getModel();
        dtm.setRowCount(0);
        ShowData();
    }//GEN-LAST:event_btnRefActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        String tenPB = txtTimKiem.getText();
        DefaultTableModel dtm = (DefaultTableModel)tblDSMH.getModel();
        dtm.setRowCount(0);
        frmCTMonHocDAO.ShowSearch(dtm,tenPB);
        tblDSMH.setModel(dtm);
    }//GEN-LAST:event_btnTimKiemActionPerformed

    public void ShowData() {
        DefaultTableModel dtm = (DefaultTableModel)tblDSMH.getModel();
        dtm.setRowCount(0);
        frmCTMonHocDAO.ShowData2(dtm);
        tblDSMH.setModel(dtm);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDong;
    private javax.swing.JButton btnQuanLi;
    private javax.swing.JButton btnRef;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbThongTinLopHoc;
    private javax.swing.JTable tblDSMH;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
