/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlttgs;

import static java.awt.SystemColor.desktop;

/**
 *
 * @author Admin
 */
public class QLTTGS extends javax.swing.JFrame {

    /**
     * Creates new form QLTTGS
     */
    public QLTTGS() {
        initComponents();
        this.setSize(800, 600);
//        this.setExtendedState(MAXIMIZED_BOTH);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
        this.mnQuanLy.setEnabled(false);
        this.mnAdmin.setEnabled(false);
        this.mnDangKi.setEnabled(false);
        this.mnuDangXuat.setEnabled(false);
        this.mnuDoiMatKhau.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        mnHeThong = new javax.swing.JMenu();
        mnuDangNhap = new javax.swing.JMenuItem();
        mnuDangXuat = new javax.swing.JMenuItem();
        mnuDoiMatKhau = new javax.swing.JMenuItem();
        mnuThoat = new javax.swing.JMenuItem();
        mnQuanLy = new javax.swing.JMenu();
        mnuQLHV = new javax.swing.JMenuItem();
        mnuQLGV = new javax.swing.JMenuItem();
        mnuQLMH = new javax.swing.JMenuItem();
        mnuQLLH = new javax.swing.JMenuItem();
        mnuQLDD = new javax.swing.JMenuItem();
        mnDangKi = new javax.swing.JMenu();
        mnuDKLH = new javax.swing.JMenuItem();
        mnAdmin = new javax.swing.JMenu();
        mnuTaiKhoan = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setBackground(new java.awt.Color(204, 204, 255));

        mnHeThong.setMnemonic('f');
        mnHeThong.setText("Hệ thống");

        mnuDangNhap.setMnemonic('s');
        mnuDangNhap.setText("Đăng Nhập");
        mnuDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDangNhapActionPerformed(evt);
            }
        });
        mnHeThong.add(mnuDangNhap);

        mnuDangXuat.setMnemonic('s');
        mnuDangXuat.setText("Đăng xuất");
        mnuDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDangXuatActionPerformed(evt);
            }
        });
        mnHeThong.add(mnuDangXuat);

        mnuDoiMatKhau.setMnemonic('x');
        mnuDoiMatKhau.setText("Đổi mật khẩu");
        mnuDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDoiMatKhauActionPerformed(evt);
            }
        });
        mnHeThong.add(mnuDoiMatKhau);

        mnuThoat.setMnemonic('x');
        mnuThoat.setText("Thoát");
        mnuThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuThoatActionPerformed(evt);
            }
        });
        mnHeThong.add(mnuThoat);

        menuBar.add(mnHeThong);

        mnQuanLy.setMnemonic('e');
        mnQuanLy.setText("Quản lý");

        mnuQLHV.setMnemonic('t');
        mnuQLHV.setText("Học viên");
        mnuQLHV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuQLHVActionPerformed(evt);
            }
        });
        mnQuanLy.add(mnuQLHV);

        mnuQLGV.setMnemonic('y');
        mnuQLGV.setText("Giảng viên");
        mnuQLGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuQLGVActionPerformed(evt);
            }
        });
        mnQuanLy.add(mnuQLGV);

        mnuQLMH.setMnemonic('p');
        mnuQLMH.setText("Môn học");
        mnuQLMH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuQLMHActionPerformed(evt);
            }
        });
        mnQuanLy.add(mnuQLMH);

        mnuQLLH.setMnemonic('d');
        mnuQLLH.setText("Lớp học");
        mnuQLLH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuQLLHActionPerformed(evt);
            }
        });
        mnQuanLy.add(mnuQLLH);

        mnuQLDD.setMnemonic('d');
        mnuQLDD.setText("Điểm danh");
        mnuQLDD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuQLDDActionPerformed(evt);
            }
        });
        mnQuanLy.add(mnuQLDD);

        menuBar.add(mnQuanLy);

        mnDangKi.setMnemonic('h');
        mnDangKi.setText("Đăng Kí Gói Học");

        mnuDKLH.setMnemonic('a');
        mnuDKLH.setText("Đăng ký");
        mnuDKLH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDKLHActionPerformed(evt);
            }
        });
        mnDangKi.add(mnuDKLH);

        menuBar.add(mnDangKi);

        mnAdmin.setText("Quản Trị Viên");

        mnuTaiKhoan.setText("Tài khoản");
        mnuTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTaiKhoanActionPerformed(evt);
            }
        });
        mnAdmin.add(mnuTaiKhoan);

        menuBar.add(mnAdmin);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDoiMatKhauActionPerformed
        frmDoiMK dmk = new frmDoiMK();
        dmk.setVisible(true);
        this.desktopPane.add(dmk);
    }//GEN-LAST:event_mnuDoiMatKhauActionPerformed

    private void mnuThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuThoatActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mnuThoatActionPerformed

    private void mnuQLMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuQLMHActionPerformed
        // TODO add your handling code here:
        frmMonHoc mh = new frmMonHoc();
        mh.setVisible(true);
        this.desktopPane.add(mh);
    }//GEN-LAST:event_mnuQLMHActionPerformed

    private void mnuQLHVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuQLHVActionPerformed
        frmHocVien hv = new frmHocVien();
        hv.setVisible(true);
        this.desktopPane.add(hv);
    }//GEN-LAST:event_mnuQLHVActionPerformed

    private void mnuDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDangNhapActionPerformed
        // TODO add your handling code here:
        frmDangNhap frm = new frmDangNhap(null, true);
        frm.setVisible(true);
        if(frm.getbKetQuaDangNhap()){
            this.mnuDangNhap.setEnabled(false);
            this.mnuDangXuat.setEnabled(true);
            this.mnQuanLy.setEnabled(true);
            this.mnDangKi.setEnabled(true);
            this.mnAdmin.setEnabled(true);
            this.mnuDoiMatKhau.setEnabled(true);
        }
        
    }//GEN-LAST:event_mnuDangNhapActionPerformed

    private void mnuDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDangXuatActionPerformed
        this.mnQuanLy.setEnabled(false);
        this.mnDangKi.setEnabled(false);
        this.mnuDangNhap.setEnabled(true);
        this.mnuDoiMatKhau.setEnabled(false);

    }//GEN-LAST:event_mnuDangXuatActionPerformed

    private void mnuQLGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuQLGVActionPerformed
        // TODO add your handling code here:
        frmGiaSu gs = new frmGiaSu();
        gs.setVisible(true);
        this.desktopPane.add(gs);
    }//GEN-LAST:event_mnuQLGVActionPerformed

    private void mnuQLLHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuQLLHActionPerformed
        // TODO add your handling code here:
        frmLopHoc lh = new frmLopHoc();
        lh.setVisible(true);
        this.desktopPane.add(lh);
    }//GEN-LAST:event_mnuQLLHActionPerformed

    private void mnuTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTaiKhoanActionPerformed
        
        frmTaiKhoan tk = new frmTaiKhoan();
        tk.setVisible(true);
        this.desktopPane.add(tk);
    }//GEN-LAST:event_mnuTaiKhoanActionPerformed

    private void mnuDKLHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDKLHActionPerformed
        // TODO add your handling code here:
        frmDangKyHoc dk = new frmDangKyHoc();
        dk.setVisible(true);
        this.desktopPane.add(dk);
    }//GEN-LAST:event_mnuDKLHActionPerformed

    private void mnuQLDDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuQLDDActionPerformed
        // TODO add your handling code here:
        frmDiemDanh dd = new frmDiemDanh();
        dd.setVisible(true);
        this.desktopPane.add(dd);
    }//GEN-LAST:event_mnuQLDDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLTTGS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLTTGS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLTTGS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLTTGS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLTTGS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu mnAdmin;
    private javax.swing.JMenu mnDangKi;
    private javax.swing.JMenu mnHeThong;
    private javax.swing.JMenu mnQuanLy;
    private javax.swing.JMenuItem mnuDKLH;
    private javax.swing.JMenuItem mnuDangNhap;
    private javax.swing.JMenuItem mnuDangXuat;
    private javax.swing.JMenuItem mnuDoiMatKhau;
    private javax.swing.JMenuItem mnuQLDD;
    private javax.swing.JMenuItem mnuQLGV;
    private javax.swing.JMenuItem mnuQLHV;
    private javax.swing.JMenuItem mnuQLLH;
    private javax.swing.JMenuItem mnuQLMH;
    private javax.swing.JMenuItem mnuTaiKhoan;
    private javax.swing.JMenuItem mnuThoat;
    // End of variables declaration//GEN-END:variables

}
